### ISSUE TITLE
Is this package suitable for Windows?

### ISSUE THREAD

**Issue by rafajot** [zeek/pysubnettree#20]
Sorry if this is a dumb question but when I run
`pip install pysubnettree`
the installation on my Win10 fails because of missing netinet/in.h which is to my knowledge Linux/Unix library. So is my assumption correct that pysubnettree is not suitable for windows at the moment? And if so are there possibly any plans to port it?

  ```
  C:\Users\xxx\AppData\Local\Temp\pip-install-llhms6k7\pysubnettree\include\patricia.h(65): fatal error C1083: Cannot open include file: 'netinet/in.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
```

**Comment by jsiwek** [comment]
It's historically never been targeted for Windows usage and no one that has helped maintain it so far has active plans to add that support.  Any contribution/help in that area would be appreciated/considered, though.
