### ISSUE TITLE
Issue When Installing

### ISSUE THREAD

**Issue by tkoch96** [zeek/pysubnettree#25]
I'm on Windows 10. 
I get an error when doing either pip or python setup.py install: " fatal error C1083: Cannot open include file: 'netinet/in.h': No such file or directory "

**Comment by tkoch96** [comment]
And if this package is not meant to work on Windows, perhaps indicate that somewhere?

**Comment by jsiwek** [comment]
Sorry, Windows is not currently supported -- I added a note about supported platforms to the `README` and added  "Operating System" classifiers to `setup.py` so that platform-support should show up on PyPI/pip.
