### ISSUE TITLE
Swig 4 issue

### ISSUE THREAD

**Issue by kitterma** [zeek/pysubnettree#29]
In Debian we switched from swig 3 to swig 4 and it did not go [well](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005044).  The specific error we get after SubnetTree_wrap.cc is regenerated with swig 4 is:

> import SubnetTree
> t = SubnetTree.SubnetTree()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>    File "/usr/lib/python3/dist-packages/SubnetTree.py", line 82, in __init__
>     _SubnetTree.SubnetTree_swiginit(self, _SubnetTree.new_SubnetTree(binary_lookup_mode))
> AttributeError: module '_SubnetTree' has no attribute 'SubnetTree_swiginit'

Any suggestions you might have on how to get this working with swig 4 would be greatly appreciated.

**Comment by kitterma** [comment]
Would be nice to get some feedback on this.

**Comment by kitterma** [comment]
By not moving the existing SubnetTree_wrap.cc out of the way before the build, doesn't your change lead to the file not being rebuilt?

**Comment by awelzel** [comment]
> By not moving the existing SubnetTree_wrap.cc out of the way before the build, doesn't your change lead to the file not being rebuilt?

Hmm, nope, I had checked. However, looking again that's actually a bug in the Makefile using `SubnetTree_wrap.cpp` as target, but then producing `SubnetTree_wrap.cc`.

That's a separate problem though. Can you check if you can reproduce the [upstream issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005044) still?

**Comment by kitterma** [comment]
I see the issue now.  Downstream (Debian) issue.  I'll close the issue.  Thanks for the help.
