### ISSUE TITLE
signal 11 during ip lookup

### ISSUE THREAD

**Issue by svivekaa** [zeek/pysubnettree#32]
our celery task is crashing occasionally with signal 11 in subnetree get_item. Ubuntu 20.04

`       if self.iptree[str(lookup_ip)]:
    (Python) File "/opt/ns/python-apps/nslogcollector/app-env/lib/python3.8/site-packages/SubnetTree.py", line 157, in __getitem__
        return _SubnetTree.SubnetTree___getitem__(self, cidr)`
        
 pysubnettree==0.33
celery==5.2.3

**Comment by awelzel** [comment]
@svivekaa - thanks for the report, signal 11 would indicate a segfault. Any chance you have coredump / backtrace of the crash (maybe collected by coredumpctl)?

Alternatively, could you get to the value of the "cidr" that's looked up and/or build a self-contained reproducer?
